"""add users and projects

Revision ID: 58d7a629e9c3
Revises: 19319ed6cf9c
Create Date: 2025-12-10 19:55:06.407398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d7a629e9c3'
down_revision: Union[str, Sequence[str], None] = '19319ed6cf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_reviews_id'), 'project_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_project_reviews_project_id'), 'project_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_reviews_teacher_id'), 'project_reviews', ['teacher_id'], unique=False)
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_column('projects', 'owner_id')
    op.drop_index(op.f('ix_project_reviews_teacher_id'), table_name='project_reviews')
    op.drop_index(op.f('ix_project_reviews_project_id'), table_name='project_reviews')
    op.drop_index(op.f('ix_project_reviews_id'), table_name='project_reviews')
    op.drop_table('project_reviews')
    # ### end Alembic commands ###
